### ISSUE TITLE
Question:  Is there a place for these commands?

### ISSUE THREAD

**Issue by jrm16020** [Netflix/hubcommander#47]
I'm sorry if this isn't the best place for this kind of conversation but I'm not sure where else to start it.

The company that I work for is a heavy user of AWS.  For that reason I'm able to make some assumptions about where my hubcommander bot would be running and the resources that it would have available to it.  I wanted to start learning Python and extend Hubcommander so I've added several commands, commands that I've put in a separate class to prevent missing out on other work that's merged here.

I'm waiting for #40 to be merged so I can refactor my code a bit.  That said, when I've been able to do that I'm curious if there's a place for more opinionated commands/functionality like the below, maybe in a separate `contrib` directory with additional instructions on how to make use of them?

- `get_credentials` method that uses EC2 SSM parameter store for retrieving credentials
- `!CreatePR` to do the obvious
- `!AddReviewerGroup`, `!RemoveReviewerGroup`, `!ListReviewerGroups`, `!DescribeReviewerGroup`, `!AddToReviewerGroup`, `!RemoveFromReviewerGroup` and finally, `!AddReviewersToPR` each would make use of SSM parameter store in some form.  The goal is to use hubcommander for creating a pull request and allowing our developers to add reviewers to their PR by group without having to provide them admin access to the repo.
- `!CheckUsername` will return the user's real name if they're still a member of your organization.  Helpful for performing cleanup on a reviewer group in case an employee leaves the company.
- `!GetPRInfo` returns the HTTP URL of a pull request 
- `!ToggleAdminBranchProtection` to do the obvious.

I wanted to ask before opening a PR.  Thank you for any input you can offer!

**Comment by jrm16020** [comment]
A good chunk of this work can and should have been done using [Github Teams](https://developer.github.com/v3/orgs/teams/).  I'll close this for now and may reopen later when I have something worth discussing.

**Comment by mikegrima** [comment]
Hello @jrm16020 :

Had some questions and suggestions.  For `get_credentials`, why use SSM instead of KMS? 

For `!ToggleAdminBranchProtection`, can that already be accomplished with `!SetBranchProtection` ?

**Comment by jrm16020** [comment]
@mikegrima SSM uses KMS to encrypt the data it holds.  I don't know for how long it's been a thing but I followed [this example](https://aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks/).  

With `!ToggleAdminBranchProtection` I was going for some of the more complex branch protection offered in the UI.  The branch protection could be what `!SetBranchProtection` supports (disabling force push and deletion) or it could mean requiring some number of PR approvers, enforcement of those standards even for admin users, etc.  Would you see `!SetBranchProtection` being where this functionality goes?

**Comment by mikegrima** [comment]
I haven't used ECS much.  But, per the docs:

> Instead of creating and distributing your AWS credentials to the containers or using the EC2 instance role, you can associate an IAM role with an ECS task definition or the RunTask API operation. For more information, see IAM Roles for Tasks.

This sounds similar to the way that on-instance credentials operate. If so, then you should be able to use KMS directly (via the examples I provided).  I mostly don't see SSM providing much value unless you want to get the creds via an encrypted environment variable. You can do that, but since I already have an example for KMS, that might be easier ¯\_(ツ)_/¯?

When I was creating the `!SetBranchProtection` feature, I kept it simple because I wasn't sure how I wanted to approach that feature. There are many bells and whistles to branch protection and I didn't have a good story for how that would work.  Now that I am mostly complete with #40 (I would like to start moving some commands over to it). I feel that with more sophisticated arg-parsing, it will be easier to add more complex features.  I would certainly like to have `!SetBranchProtection` be able to handle these extra use cases.

**Comment by jrm16020** [comment]
I'll see what I can get done with respect to some of the additional branch protection functionality and send a PR to see what you think.
